language: php

cache:
  - apt

php:
  - 5.6

install:
  - composer self-update
  - composer --prefer-source install
  - composer require ovr/spellcheck-cli:*

script:
  - ./vendor/bin/spellchecker --exit-code-with-miss-takes=1 --ext=md --language=ru check app/_posts/ru/2015/ 
  - ./vendor/bin/spellchecker --exit-code-with-miss-takes=1 --ext=md --language=ru check app/_posts/ru/2014/
  - ./vendor/bin/spellchecker --exit-code-with-miss-takes=1 --ext=md --language=en check app/_posts/en/2014/ 
  - ./vendor/bin/spellchecker --exit-code-with-miss-takes=1 --ext=md --language=en check app/_posts/en/2015/
